### ISSUE TITLE
建议增加requirements.txt文件

### ISSUE THREAD

**Issue by lilithttf** [sixone-Jiang/LHCXAutoFishingScripts#1]
安装依赖的时候比较方便，并且能够锁定版本
这是用pipreqs生成的示例
```
opencv_python==4.5.5.64
PyAutoGUI==0.9.53
pywin32==304
win32gui==221.6
```

**Comment by sixone-Jiang** [comment]
新版本即将更新，谢谢您提供的宝贵意见


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sixone-Jiang/LHCXAutoFishingScripts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月22日(星期一) 上午10:29
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[sixone-Jiang/LHCXAutoFishingScripts] 建议增加requirements.txt文件 (Issue #1)





 
安装依赖的时候比较方便，并且能够锁定版本
 这是用pipreqs生成的示例
 opencv_python==4.5.5.64 PyAutoGUI==0.9.53 pywin32==304 win32gui==221.6
