### ISSUE TITLE
adb无法连接

### ISSUE THREAD

**Issue by Greatmean** [sixone-Jiang/LHCXAutoFishingScripts#2]
使用的是雷电模拟器，之前能成功连接adb运行脚本，但之后使用时遇到“检测到设备离线”的问题，重启电脑、管理员身份打开模拟器和cmd、拷贝脚本adb至模拟器目录均无法解决（俺是小白，mumu模拟器疯狂闪退所以才用的雷电
===============CMD================
Microsoft Windows [版本 10.0.19044.2006]
(c) Microsoft Corporation。保留所有权利。

C:\Windows\system32>d:

D:\>cd other

D:\other>cd SoulTideScripts

D:\other\SoulTideScripts>cd LHCXAutoFishingScripts-main

D:\other\SoulTideScripts\LHCXAutoFishingScripts-main>conda activate lhcx

(lhcx) D:\other\SoulTideScripts\LHCXAutoFishingScripts-main>python main.py
ADB PATH >>>> D:/other/SoulTideScripts/LHCXAutoFishingScripts-main/adb/adb.exe
检测设备连接状态 >>> 127.0.0.1:5555 ...
adb server version (31) doesn't match this client (41); killing...
* daemon started successfully

设备列表：
127.0.0.1:5555  offline
emulator-5554   device

检测到设备离线！！！
由于不同模拟器ADB实现细节不同，请尝试以下办法（没有先后顺序）：
· 重启模拟器
· 如果模拟器已经自带了ADB，则可以尝试将脚本中adb文件夹的文件拷贝至模拟器自带ADB目录。注意备份原文件
· 在adb目录下打开cmd，执行 adb kill-server 后再执行 adb start-server，然后执行 adb devices 查看是否解决
· 重启电脑
· 换个模拟器

(lhcx) D:\other\SoulTideScripts\LHCXAutoFishingScripts-main>

===============config.ini===============
# 该文件不会生效请自行拷贝一份为config.ini
# 配置文件
[default]

# ADB连接地址和端口号。
#
# 必需配置，程序会寻找此地址的设备，找不到则自动终止。
# 不同模拟器默认端口号不同, MUMU 为7555
adb_host_port = 127.0.0.1:5555

# 最大结束轮次，默认60
end_times = 100

# 钓到几条新鱼后停止, 0表示不启用该功能, 1 表示启用该功能
new_fish_stop = 1

# 使用自动定位模拟器位置， 0为无效
auto_loc = 1

# 模拟器窗口的名称，用于自动找窗口,
# 注意，您的模拟器名称可能与我不同，该参数仅在auto_loc=1时生效
title_name = 雷电模拟器

# -----如果没有出错，以下可以不配置

# 自动定位出错时，请将auto_loc = 0, 然后自行测定以下参数
# 自行测量屏幕中钓鱼显示框左边界和上边界位置
mumu_left = 950
mumu_top = 605
# 自行找一个屏幕中方便点击的初始点（要位于模拟器内）
x_origin = 1000
y_origin = 1000

===============main.py===============
from common.AutoAdb import AutoAdb
from bin.RunApi import RunApi

AutoAdb(test_device=True)
adb = AutoAdb()
# 鱼饵选择
# 例如填入 baits_list = [1, 2]将自动钓蚯蚓，蚯蚓掉完后钓骨渣，不填入默认第一个
baits_list = [2]
# 对照表：
#       蚯蚓    骨渣    青虫    白虫    红虫    蟋蟀    肉团    虫蛹    碎肉    虾米
#        1      2       3       4       5       6       7       8       9      10
# 掉落范围：
# 绿色 1-5 蓝色 51-53 紫色 81-83 橙色 111-113, 按顺序递推
# 具体概率见wiki.biligame/lhcx

RunApi.run_fish(adb, baits_list)
#RunApi.run_rpg(adb,RPG_map=rpg_map, rpg_time=rpg_map2)

**Comment by sixone-Jiang** [comment]
该问题我不曾遇到，不像是常见问题，大概是电脑某种配置导致的？代码即将迎来更新，你可以重新下载代码试试
